export const GET_INBOX_INDIVIDUAL_MAIL = 'GET_INBOX_INDIVIDUAL_MAIL';
export const GET_INBOX_GROUP_MAIL = 'GET_INBOX_GROUP_MAIL';
export const SEND_MAIL = 'SEND_MAIL';
export const GET_SENT_MAIL = 'GET_SENT_MAIL';
export const GET_DRAFT_MAIL = 'GET_DRAFT_MAIL';
